apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: ai-obs
stringData:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'your_email@gmail.com'
      smtp_auth_username: 'your_email@gmail.com'
      smtp_auth_password: 'APP_PASSWORD'

    route:
      receiver: email

    receivers:
    - name: email
      email_configs:
      - to: 'manager@gmail.com'
        send_resolved: true
