apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-service-monitor
  namespace: ai-obs
  labels:
    team: ai
spec:
  namespaceSelector:
    matchNames:
    - ai-obs
  selector:
    matchLabels:
      app: ai-service
  endpoints:
  - port: http
    path: /metrics
    interval: 5s
