grafana:
  enabled: true
  adminPassword: admin
  sidecar:
    dashboards:
      enabled: true

alertmanager:
  enabled: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUseHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        team: ai
    serviceMonitornamespaceSelector:
      matchNames:
      - ai-obs
    ruleSelector:
      matchLabels:
        team: ai
